var Suggestions_Locations = ["Mumbai", "Delhi", "Bengaluru", "Hyderabad"];
const Suggestions_CarNames = ["Ford Mondeo", "Honda CRV"];//, "Tata Altroz", "Ciaz", "Tata Nexon"];
const Suggestions_TravelDates = ["Today", "Tomorrow", "3 days after today", "Enter date"];
const Suggestions_NoTrainsAvailable = ["Change date", "Change dest (Go to 1)", "Start over (Go to 0)"];
const Suggestions_TrainClasses = ["EC", "1AC", "2AC", "3AC", "Change dest (Go to 1)", "Start over (Go to 0)"];
const Suggestions_PaymentCompleted = ["Payment Completed"];
const validSeatNumber = [1, 2, 3, 4, 5, 6];
const validSeatRow = ['a', 'b', 'c'];
var startTime = "";